version: '3.7'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: currencymail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_key
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - gorate
  ses4case:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_CONN: ${DB_CONN}
      API_KEY: ${API_KEY}
      GM_APP_PASSWORD: ${GM_APP_PASSWORD}
    networks:
      - gorate
    depends_on:
      database:
        condition: service_healthy
networks:
    gorate:
        driver: bridge